name       : sndio
version    : 1.8.1
release    : 7
source     :
    - https://github.com/ratchov/sndio/archive/refs/tags/release_1_8_1.tar.gz : b6f4d6816c8a0b507fd5364f9f7adc9555b568d415330d1d600ac10116a13f2e
license    : ISC
component  : multimedia.audio
summary    : Sndio is a small audio and MIDI framework
description: |
    Sndio is a small audio and MIDI framework part of the OpenBSD project and ported to FreeBSD, Linux and NetBSD.
    It provides a lightweight audio & MIDI server and a fully documented user-space API to access either the server or directly the hardware in a uniform way.
    Sndio is designed to work for desktop applications, but pays special attention to synchronization mechanisms and reliability required by music applications. Reliability through simplicity are part of the project goals.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
setup      : |
    ./configure --prefix=/usr --libdir=%libdir% --mandir=/usr/share/man --datadir=/usr/share
build      : |
    %make
install    : |
    %make_install
