name       : sndio
version    : 1.4.0
release    : 3
source     :
    - http://www.sndio.org/sndio-1.4.0.tar.gz : 68713db624797dbff69c0f4ce1b24054fb0803da340508edbc5e08d6778f9781
license    : ISC
component  : multimedia.audio
summary    : Sndio is a small audio and MIDI framework
description: |
    Sndio is a small audio and MIDI framework part of the OpenBSD project and ported to FreeBSD, Linux and NetBSD.
    It provides a lightweight audio & MIDI server and a fully documented user-space API to access either the server or directly the hardware in a uniform way.
    Sndio is designed to work for desktop applications, but pays special attention to synchronization mechanisms and reliability required by music applications. Reliability through simplicity are part of the project goals.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
setup      : |
    ./configure --prefix=/usr --libdir=%libdir% --mandir=/usr/share/man --datadir=/usr/share
build      : |
    %make
install    : |
    %make_install
